import { Job, UserProfile } from '@/types';

export const mockJobs: Job[] = [
  {
    id: '1',
    title: 'New Grad Systems Engineer',
    company: 'Collins Aerospace',
    location: 'Cedar Rapids, IA',
    remote: 'Hybrid',
    postedDate: '2026-05-30',
    salary: '$72,000 - $88,000',
    fitScore: 96,
    matchReasons: [
      'Location matches preferred area (Cedar Rapids, IA)',
      'Entry-level/new-grad role aligns with graduation timeline',
      'Systems engineering focus matches career interest',
      'Avionics domain matches manufacturing background',
      'GD&T and technical documentation skills match requirements',
    ],
    missingKeywords: ['DO-178C', 'Model-Based Systems Engineering'],
    description:
      'Join Collins Aerospace as a New Graduate Systems Engineer working on next-generation avionics systems. You will collaborate with cross-functional teams to define system requirements, conduct trade studies, and support integration testing of flight-critical hardware and software.',
    requiredSkills: ['Systems Engineering', 'MATLAB', 'Technical Documentation', 'GD&T'],
    preferredSkills: ['Python', 'DO-178C', 'MBSE', 'Avionics'],
    status: 'New',
    url: '#',
    department: 'Avionics Systems',
    experienceLevel: 'Entry-Level',
    saved: true,
  },
  {
    id: '2',
    title: 'Manufacturing Engineer I – New Product Introduction',
    company: 'GE Aerospace',
    location: 'Evendale, OH',
    remote: 'On-site',
    postedDate: '2026-05-29',
    salary: '$68,000 - $82,000',
    fitScore: 91,
    matchReasons: [
      'NPI focus directly matches stated career interest',
      'Manufacturing engineering role aligns with skill set',
      'CAD proficiency (SolidWorks) matches job requirements',
      'Lean/5S experience is a key differentiator',
      'Aerospace company in target list',
    ],
    missingKeywords: ['AS9100', 'ERP Systems', 'Six Sigma Green Belt'],
    description:
      'GE Aerospace is seeking a Manufacturing Engineer I to support New Product Introduction (NPI) activities for commercial and military jet engine components. You will work with design teams to develop manufacturing processes, tooling, and production plans.',
    requiredSkills: ['SolidWorks', 'Manufacturing Processes', 'Lean Manufacturing', 'NPI'],
    preferredSkills: ['AS9100', 'Six Sigma', 'ERP', 'GD&T'],
    status: 'Interested',
    url: '#',
    department: 'Manufacturing Engineering',
    experienceLevel: 'Entry-Level',
    saved: true,
  },
  {
    id: '3',
    title: 'Flight Controls Engineer – New Graduate',
    company: 'Boeing',
    location: 'St. Louis, MO',
    remote: 'Hybrid',
    postedDate: '2026-05-28',
    salary: '$74,000 - $91,000',
    fitScore: 88,
    matchReasons: [
      'Flight controls specialization matches stated interest',
      'MATLAB/Python proficiency directly required',
      'Aerospace engineering degree is a perfect match',
      'New graduate program aligned with December graduation',
    ],
    missingKeywords: ['Simulink', 'Control Systems Theory', 'Flight Test Experience'],
    description:
      'Boeing is hiring new graduate Flight Controls Engineers for our defense programs. You will develop and verify flight control laws, perform simulation studies, and support flight test activities. Must have strong analytical and programming skills.',
    requiredSkills: ['MATLAB', 'Python', 'Control Theory', 'Aerospace Engineering'],
    preferredSkills: ['Simulink', 'Flight Test', 'DO-178C', 'C++'],
    status: 'Applied',
    url: '#',
    department: 'Flight Systems',
    experienceLevel: 'Entry-Level',
    saved: true,
  },
  {
    id: '4',
    title: 'Quality Engineer – NDE Specialist',
    company: 'Honeywell',
    location: 'Minneapolis, MN',
    remote: 'On-site',
    postedDate: '2026-05-27',
    salary: '$65,000 - $79,000',
    fitScore: 85,
    matchReasons: [
      'NDE/Quality engineering matches career interest',
      'Location in Minneapolis matches preferred area',
      'Manufacturing background supports quality focus',
      'Technical documentation skills are highly relevant',
    ],
    missingKeywords: ['NDT Level II Certification', 'CMM Operation', 'PPAP'],
    description:
      'Honeywell Aerospace is looking for a Quality Engineer specializing in Non-Destructive Evaluation (NDE) for aerospace components. You will develop inspection plans, analyze defects, and work with suppliers to maintain quality standards.',
    requiredSkills: ['NDE/NDT', 'Quality Systems', 'Technical Documentation', 'GD&T'],
    preferredSkills: ['AS9100', 'PPAP', 'CMM', 'Six Sigma'],
    status: 'New',
    url: '#',
    department: 'Quality Assurance',
    experienceLevel: 'Entry-Level',
    saved: false,
  },
  {
    id: '5',
    title: 'Avionics Systems Engineer',
    company: 'Garmin',
    location: 'Olathe, KS',
    remote: 'Hybrid',
    postedDate: '2026-05-26',
    salary: '$70,000 - $86,000',
    fitScore: 83,
    matchReasons: [
      'Avionics manufacturing experience is a strong match',
      'Systems engineering focus aligns with role',
      'Python and MATLAB skills required and present',
      'Garmin is a target company',
    ],
    missingKeywords: ['DO-254', 'FAA Certification Process', 'VHDL'],
    description:
      'Garmin is seeking an Avionics Systems Engineer to support development of certified aircraft navigation and communication systems. You will define system requirements, coordinate with hardware and software teams, and support DO-254/DO-178 certification activities.',
    requiredSkills: ['Systems Engineering', 'Avionics', 'Python', 'MATLAB'],
    preferredSkills: ['DO-254', 'DO-178', 'FAA Regulations', 'VHDL'],
    status: 'New',
    url: '#',
    department: 'Aviation Systems',
    experienceLevel: 'Entry-Level',
    saved: false,
  },
  {
    id: '6',
    title: 'Test Engineer – Structural Systems',
    company: 'Northrop Grumman',
    location: 'Melbourne, FL',
    remote: 'On-site',
    postedDate: '2026-05-25',
    salary: '$76,000 - $94,000',
    fitScore: 79,
    matchReasons: [
      'Test engineering aligns with stated career interest',
      'Defense aerospace domain matches background',
      'MATLAB scripting skills are directly applicable',
      'Aerospace engineering degree is required',
    ],
    missingKeywords: ['LabVIEW', 'NI DAQ', 'Structural Test Procedures', 'Security Clearance'],
    description:
      'Northrop Grumman seeks a Test Engineer to plan, execute, and analyze structural tests for next-generation defense aircraft programs. You will develop test plans, set up data acquisition systems, and generate test reports supporting airworthiness certification.',
    requiredSkills: ['Test Engineering', 'MATLAB', 'Aerospace Engineering', 'Data Analysis'],
    preferredSkills: ['LabVIEW', 'NI DAQ', 'Python', 'Structural Analysis'],
    status: 'New',
    url: '#',
    department: 'Structural Test',
    experienceLevel: 'Entry-Level',
    saved: false,
  },
  {
    id: '7',
    title: 'Mechanical Design Engineer – Early Career',
    company: 'Lockheed Martin',
    location: 'Fort Worth, TX',
    remote: 'On-site',
    postedDate: '2026-05-24',
    salary: '$78,000 - $96,000',
    fitScore: 77,
    matchReasons: [
      'CAD proficiency (SolidWorks, Onshape) matches requirements',
      'GD&T expertise is highly relevant',
      'Aerospace engineering background fits the domain',
      'Defense company in target list',
    ],
    missingKeywords: ['CATIA V5', 'PDM Systems', 'Composite Design'],
    description:
      'Lockheed Martin is hiring an Early Career Mechanical Design Engineer for the F-35 program. You will design and analyze structural and mechanical components, create detailed drawings, and collaborate with manufacturing to ensure producibility.',
    requiredSkills: ['CATIA or SolidWorks', 'GD&T', 'Mechanical Design', 'Finite Element Analysis'],
    preferredSkills: ['CATIA V5', 'Composite Materials', 'PDM', 'Python scripting'],
    status: 'New',
    url: '#',
    department: 'Airframe Design',
    experienceLevel: 'Entry-Level',
    saved: false,
  },
  {
    id: '8',
    title: 'Manufacturing Systems Engineer',
    company: 'Textron Aviation',
    location: 'Wichita, KS',
    remote: 'Hybrid',
    postedDate: '2026-05-23',
    salary: '$66,000 - $80,000',
    fitScore: 82,
    matchReasons: [
      'Manufacturing focus aligns with experience',
      'Lean/5S skills are directly listed as requirements',
      'Systems-level thinking matches role scope',
      'Textron is a target company',
    ],
    missingKeywords: ['Value Stream Mapping', 'AutoCAD', 'MES Systems'],
    description:
      'Textron Aviation is looking for a Manufacturing Systems Engineer to optimize production systems for Cessna and Beechcraft aircraft. You will lead Lean/5S initiatives, analyze production data, and drive continuous improvement projects.',
    requiredSkills: ['Lean Manufacturing', '5S', 'Manufacturing Systems', 'Data Analysis'],
    preferredSkills: ['Value Stream Mapping', 'AutoCAD', 'Excel/VBA', 'Six Sigma'],
    status: 'Interested',
    url: '#',
    department: 'Manufacturing Engineering',
    experienceLevel: 'Entry-Level',
    saved: true,
  },
  {
    id: '9',
    title: 'Systems Integration Engineer – Defense',
    company: 'Collins Aerospace',
    location: 'Rockford, IL',
    remote: 'Hybrid',
    postedDate: '2026-05-22',
    salary: '$71,000 - $87,000',
    fitScore: 89,
    matchReasons: [
      'Illinois location matches preferred area',
      'Collins Aerospace is a target company',
      'Systems integration aligns with aerospace engineering focus',
      'Technical documentation skills are required',
      'Avionics manufacturing background is highly relevant',
    ],
    missingKeywords: ['DOORS', 'Model-Based Systems Engineering', 'ICD Development'],
    description:
      'Collins Aerospace seeks a Systems Integration Engineer to support defense avionics programs in Rockford, IL. You will lead system integration activities, manage interface definitions, and support lab and flight testing.',
    requiredSkills: ['Systems Integration', 'Avionics', 'Technical Documentation', 'Testing'],
    preferredSkills: ['DOORS', 'MBSE', 'Python', 'ICD'],
    status: 'New',
    url: '#',
    department: 'Defense Systems',
    experienceLevel: 'Entry-Level',
    saved: true,
  },
  {
    id: '10',
    title: 'Propulsion Test Engineer – New Grad',
    company: 'GE Aerospace',
    location: 'Peebles, OH',
    remote: 'On-site',
    postedDate: '2026-05-21',
    salary: '$70,000 - $85,000',
    fitScore: 75,
    matchReasons: [
      'Test engineering interest matches role',
      'MATLAB/Python required and available',
      'Aerospace engineering degree is essential',
    ],
    missingKeywords: ['Combustion Testing', 'LabVIEW', 'Propulsion Systems', 'NI Hardware'],
    description:
      'GE Aerospace is hiring a Propulsion Test Engineer at the world-class Peebles Test Operations facility. You will plan and execute jet engine tests, develop test procedures, and analyze performance data for next-generation propulsion systems.',
    requiredSkills: ['Test Engineering', 'MATLAB', 'Data Analysis', 'Aerospace Engineering'],
    preferredSkills: ['LabVIEW', 'Propulsion', 'Python', 'NI DAQ'],
    status: 'New',
    url: '#',
    department: 'Propulsion Test',
    experienceLevel: 'Entry-Level',
    saved: false,
  },
  {
    id: '11',
    title: 'Avionics Manufacturing Engineer',
    company: 'Collins Aerospace',
    location: 'Cedar Rapids, IA',
    remote: 'On-site',
    postedDate: '2026-05-20',
    salary: '$67,000 - $82,000',
    fitScore: 94,
    matchReasons: [
      'Cedar Rapids location is top preferred area',
      'Avionics manufacturing experience is a direct match',
      'Collins Aerospace is the top target company',
      'NDE background aligns with quality requirements',
      'Lean/5S experience is directly applicable',
    ],
    missingKeywords: ['IPC-A-610', 'J-STD-001', 'AOI Systems'],
    description:
      'Collins Aerospace Cedar Rapids is seeking an Avionics Manufacturing Engineer to support production of advanced avionics products. You will develop manufacturing processes, support NPI activities, and drive quality improvements on the production floor.',
    requiredSkills: ['Manufacturing Engineering', 'Avionics', 'NDE', 'Process Improvement'],
    preferredSkills: ['IPC Standards', 'Lean', 'SolidWorks', 'Python'],
    status: 'Interviewing',
    url: '#',
    department: 'Avionics Manufacturing',
    experienceLevel: 'Entry-Level',
    saved: true,
  },
  {
    id: '12',
    title: 'Systems Engineer – Rotary Wing',
    company: 'Lockheed Martin',
    location: 'Owego, NY',
    remote: 'On-site',
    postedDate: '2026-05-19',
    salary: '$75,000 - $92,000',
    fitScore: 72,
    matchReasons: [
      'Systems engineering focus matches interest',
      'Defense domain aligns with background',
      'MATLAB skills are required',
    ],
    missingKeywords: ['Rotorcraft Systems', 'MIL-STD-1553', 'Systems Architecture', 'DOORS'],
    description:
      'Lockheed Martin is seeking a Systems Engineer for rotary wing programs at our Owego, NY site. You will develop system architectures, write requirements, and support integration and test of mission systems for military helicopter programs.',
    requiredSkills: ['Systems Engineering', 'Requirements Management', 'MATLAB', 'Defense'],
    preferredSkills: ['DOORS', 'MIL-STD-1553', 'Rotorcraft', 'MBSE'],
    status: 'New',
    url: '#',
    department: 'Mission Systems',
    experienceLevel: 'Entry-Level',
    saved: false,
  },
];

export const defaultUserProfile: UserProfile = {
  name: 'Nolan Benson',
  email: 'nolanbenson24@gmail.com',
  degree: 'Bachelor of Science in Aerospace Engineering',
  graduationDate: 'December 2026',
  university: 'Iowa State University',
  skills: [
    'CAD', 'Onshape', 'SolidWorks', 'KeyShot', 'MATLAB', 'Python',
    'Excel', 'GD&T', 'Lean/5S', 'Manufacturing Support', 'Avionics Manufacturing',
    'NDE', 'Systems-Level Problem Solving', 'Technical Documentation',
  ],
  targetTitles: [
    'Systems Engineer', 'Manufacturing Engineer', 'NPI Engineer',
    'Flight Controls Engineer', 'Test Engineer', 'Quality Engineer',
    'Avionics Engineer', 'Aerospace Engineer',
  ],
  targetCompanies: [
    'Collins Aerospace', 'Boeing', 'Northrop Grumman', 'Lockheed Martin',
    'GE Aerospace', 'Honeywell', 'Garmin', 'Textron',
  ],
  preferredLocations: [
    'Iowa', 'Illinois', 'Minnesota', 'Cedar Rapids, IA',
    'Chicago, IL', 'Minneapolis, MN',
  ],
  remotePreference: ['Remote', 'Hybrid', 'On-site'],
};
